CC    = g++
SDIR     = .
IFLAGS = -O2 -c -I$(SDIR)
LFLAGS   = -lm -lgslcblas
HEADERS  = $(SDIR)/auxFuncs.h $(SDIR)/global.h
OBJECTS  = ar1.o kGrid.o vfInit.o binaryVal.o vfStep.o gridMax.o binaryMax.o global.o

main : 		main.o $(OBJECTS) $(HEADERS)
		$(CC) -m64 -o main main.o $(OBJECTS) $(LFLAGS) 

clean :
	rm -f *.o
	rm -f core core.*

veryclean :
	rm -f *.o
	rm -f core core.*
	rm -f *.linkinfo
	rm -f main
